name: Fetch YouTube Videos

on:
  schedule:
    - cron: "0 */6 * * *" # 6時間ごと
  workflow_dispatch: # 手動実行も可能

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # チャンネル情報から「アップロード動画」プレイリストIDを取得
      - name: Get uploads playlist ID
        run: |
          curl -s \
          "https://www.googleapis.com/youtube/v3/channels?key=${{ secrets.YOUTUBE_API_KEY }}&id=UCVQQV-d7xKaWNdr5xcssFjQ&part=contentDetails" \
          > channel.json

          UPLOADS_ID=$(jq -r '.items[0].contentDetails.relatedPlaylists.uploads' channel.json)

          echo "UPLOADS_ID=$UPLOADS_ID" >> $GITHUB_ENV
          echo "Uploads playlist: $UPLOADS_ID"

      # アップロード動画一覧から最新5本を取得
      - name: Fetch videos
        run: |
          curl -s \
          "https://www.googleapis.com/youtube/v3/playlistItems?key=${{ secrets.YOUTUBE_API_KEY }}&playlistId=${{ env.UPLOADS_ID }}&part=snippet&maxResults=5" \
          > data.json

      - name: Convert JSON
        run: |
          jq '[
            .items[] |
            {
              id: .snippet.resourceId.videoId,
              thumbnail: .snippet.thumbnails.high.url
            }
          ]' data.json > videos.json

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add videos.json
          git commit -m "update videos" || echo "no changes"
          git push
